# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adas.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'adas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nadas.proto\x12\x04\x61\x64\x61s\"H\n\x0c\x46rameRequest\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x13\n\x0bimage_bytes\x18\x03 \x01(\x0c\"\x9d\x01\n\x0fVehicleResponse\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x12\n\nrisk_level\x18\x03 \x01(\t\x12\x11\n\talert_msg\x18\x04 \x01(\t\x12\x17\n\x0f\x63\x61mera_occluded\x18\x05 \x01(\x08\x12%\n\x07objects\x18\x06 \x03(\x0b\x32\x14.adas.DetectedObject\"e\n\x0e\x44\x65tectedObject\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x12\r\n\x05\x63olor\x18\x04 \x01(\t\x12\x0c\n\x04\x62\x62ox\x18\x05 \x03(\x02\x32S\n\x16VehicleAnalysisService\x12\x39\n\x0c\x41nalyzeFrame\x12\x12.adas.FrameRequest\x1a\x15.adas.VehicleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=20
  _globals['_FRAMEREQUEST']._serialized_end=92
  _globals['_VEHICLERESPONSE']._serialized_start=95
  _globals['_VEHICLERESPONSE']._serialized_end=252
  _globals['_DETECTEDOBJECT']._serialized_start=254
  _globals['_DETECTEDOBJECT']._serialized_end=355
  _globals['_VEHICLEANALYSISSERVICE']._serialized_start=357
  _globals['_VEHICLEANALYSISSERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
