# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adas_pb2 as adas__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleAnalysisServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeFrame = channel.unary_unary(
                '/adas.VehicleAnalysisService/AnalyzeFrame',
                request_serializer=adas__pb2.FrameRequest.SerializeToString,
                response_deserializer=adas__pb2.VehicleResponse.FromString,
                _registered_method=True)


class VehicleAnalysisServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFrame,
                    request_deserializer=adas__pb2.FrameRequest.FromString,
                    response_serializer=adas__pb2.VehicleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adas.VehicleAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adas.VehicleAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleAnalysisService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adas.VehicleAnalysisService/AnalyzeFrame',
            adas__pb2.FrameRequest.SerializeToString,
            adas__pb2.VehicleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
